### ISSUE TITLE
Publish Date

### ISSUE THREAD

**Issue by dasmehdix** [timniiler/gaitdata#2]
Hi ,
When will you publish your dataset?

**Comment by timniiler** [comment]
Hi dasmehdix - I have pushed more data here: https://github.com/timniiler/gaitdata/tree/gaitdata-S0-S39-v1 (40 subjects in both c3d and trc [tracked ascii] formats).  Subject 2 was repeated later for reliability testing.  Let me know if you have other questions.  (Note that not all the trc files are repeated in the c3d file format due to my lack of access to certain data at this time due to the COVID-19 lockdown).

**Comment by dasmehdix** [comment]
@timniiler Much thanks for share sir.
